version: "3.9"
services:
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./config/prometheus/alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - localprom
    ports:
      - 9093:9093
  cache:
    image: 'redis:latest'
    restart: 'on-failure'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
  gamebot:
    build: game_bot
    command: python main.py
    depends_on:
      - cache
      - platform
    env_file:
      - config/game_bot/.env
    #profiles: ["cli-only"]
    volumes:
      - ./game_bot:/src
  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    image: grafana/grafana
    networks:
      - localprom
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100
  platform:
    build: platform 
    command:
      - ./start-web-server
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    env_file:
      - config/platform/.env
    environment:
      - DEBUG=${DEBUG}
    memswap_limit: 16G
    ports:
      - "8000:8000"
    volumes:
      - ./platform/web_server:/src
  postgres:
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./config/prometheus/rules.yml:/etc/prometheus/rules.yml"
    networks:
      - localprom
    ports:
      - 9090:9090

networks:
  #localdev:
  #  attachable: true
  #  driver: host
  #  ipam:
  #    config:
  #      - subnet: 172.20.0.0/24
  localprom:
    driver: bridge
  
